string = str(input())
print(string[2])
print(string[len(string)-2])
print(string[:5])
print(string[0:len(string)-2])
print(string[::2])
print(string[1::2])
print(string[::-1])
print(string[len(string)::-2])
print(len(string))
